### ISSUE TITLE
Any known issues with multiple DumbCollections?

### ISSUE THREAD

**Issue by jawaidss** [richsilv/meteor-dumb-collections#4]
I am using `richsilv:dumb-collections  1.1.3` and `Meteor 1.0.3.1`.

In `client/lib/collections.js`

```javascript
Cars = new DumbCollection('cars');
Trains = new DumbCollection('trains');
```

`Cars.find()` and `Trains.find()` are interfering. For example, once I insert two cars, there should be two cars and zero trains. However, both queries return the same two results. If I then insert a train, both queries will return the same three results.

**Comment by jawaidss** [comment]
cc @max-nova

**Comment by richsilv** [comment]
Thanks for raising - I'm looking at this now.

**Comment by jawaidss** [comment]
@richsilv Thanks!

This is just a hunch, but could it be how we're initializing the underlying `Mongo.Collection`?

https://github.com/richsilv/meteor-dumb-collections/blob/master/richsilv:dumb-collections.js#L75

Maybe

```javascript
new Mongo.Collection(null);
```

should be

```javascript
new Mongo.Collection(name, {connection: null});
```

since there can only be one unnamed collection.

**Comment by jawaidss** [comment]
@richsilv While we're in there, can we make it possible to pass other `Mongo.Collection` options to the constructor too?

**Comment by richsilv** [comment]
All done.  It was a pretty stupid piece of pseudo-classical inheritance, which left all Dumb Collections referring to the same underlying collection, now resolved with a far more sensible functional pattern.

I've also allowed the ability to pass options.  I've done a quick test passing a transform, which worked fine, but let me know if you have any problems.

**Comment by jawaidss** [comment]
@richsilv Thanks! Both changes work for me.

cc @max-nova
