### ISSUE TITLE
.ironRouterReay() incorrect

### ISSUE THREAD

**Issue by Colecf** [richsilv/meteor-dumb-collections#6]
So I'm trying to make a page wait for a dumbcollection sync before displaying, but around half the time (sometimes it works, I think when I already have the necessary element in localStorage) I get stuck on the loading screen. When on the loading screen, I enter this into the chrome developer console:

    classCollection.ready()
    true
    classCollection.ironRouterReady().ready()
    false

So for some reason ironRouterReady() doesn't seem to ever be updating to true. This is the routing code:

```
Router.route('/classinfo/:classNum', {
  onRun: function() {
    classCollection.sync({retain: true, query:{classNum: this.params.classNum}});
    this.next();
  },
  loadingTemplate: 'loading',
  waitOn: function() {
    return classCollection.ironRouterReady();
  },
  action: function() {
    var classNum = parseInt(this.params.classNum);
    if(classNum === NaN) {
      this.render('unknownClass');
      return;
    }
    var theClass = classCollection.findOne({classNum: classNum});
    if(theClass) {
      this.render("classDetails", { data: function() {
        return theClass;
      }});
    } else {
      this.render('unknownClass');
    }
  },
});
```

**Comment by richsilv** [comment]
Thanks for raising.

`ironRouterReady().ready()` returns a reactive variable which gives the synced status of the collection, whereas `ready()` just indicates whether it's ready to be used (i.e. localStorage has been checked and docs inserted), so they're different things.

The problem here was that passing `retain` or `reject` prevented the `synced` flag ever being set due to a bug, which is why `ironRouterReady().ready()` was always false if there were extra docs to be added from the server.

I've just published a new version correcting this bug.  Thanks.

**Comment by Colecf** [comment]
Ok, that fixed it so now I can get past the loading screen, but now it doesn't appear to be retrieving any new documents from the server. I added a `console.log(classNum);` and `console.log(theClass);` right after the .findOne() call and even though classNum is valid, theClass is undefined. 

I can use the meteor mongo interface and call `db.classes.find({classNum: 42476})`, the same classNum that's in the url parameter, and it returns the correct class.

In fact, no documents are loaded into the collection. In the chrome console, `classCollection.findOne({});` returns undefined. (while I'm on the unknownClass template page) And when the page first loads, the console says `Dumb Collection classes seeded with 0 docs from local storage.
Dumb Collection classes now has 0 documents stored locally.`

However, my home page still works. In it, I have a `classCollection.sync({query: {term: Session.get('viewingTerm')}, syncCallback: function(){}});` in `Meteor.startup()` which does correctly load classes. However, if I then click a button that has a `Router.go('/classinfo/'+id);` call I get the error `Error: Cannot sync whilst already syncing [already_syncing]`. This happens even though meteor.startup() doesn't get called again. However if I remove the sync call on the main page the error goes away and I get the issue described above. (I had been describing the issue with the homepage's sync call removed)

**Comment by richsilv** [comment]
do you have a repo I can look at, @Colecf ?

**Comment by Colecf** [comment]
Well I tried to reproduce the errors in a small app but now I'm getting new ones. https://github.com/Colecf/DumbcollectionsErrors

I now get this:
Uncaught Error: Meteor requires document _id fields to be non-empty strings or ObjectIDs
debug.js:41 Exception in callback of async function: ReferenceError: myCollection is not defined

Which is weird because db.myCollection.find() shows every entry as having a unique, valid, ObjectID
